; Listing generated by Microsoft (R) Optimizing Compiler Version 19.13.26129.0 

	TITLE	C:\Users\przemyslaw.kleszcz\Desktop\New folder (4)\memtest2\MemTest_Vect_VS2012\stdafx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	___@@_PchSym_@00@UfhvihUkiavnbhozdOpovhaxaUwvhpglkUmvdLulowviLSETUnvngvhgCUnvngvhgPevxgPehCABCUwvyftUhgwzucOlyq@4B2008FD98C1DD4
;	COMDAT ___@@_PchSym_@00@UfhvihUkiavnbhozdOpovhaxaUwvhpglkUmvdLulowviLSETUnvngvhgCUnvngvhgPevxgPehCABCUwvyftUhgwzucOlyq@4B2008FD98C1DD4
_BSS	SEGMENT
___@@_PchSym_@00@UfhvihUkiavnbhozdOpovhaxaUwvhpglkUmvdLulowviLSETUnvngvhgCUnvngvhgPevxgPehCABCUwvyftUhgwzucOlyq@4B2008FD98C1DD4 DD 01H DUP (?)
_BSS	ENDS
END
