; Listing generated by Microsoft (R) Optimizing Compiler Version 19.13.26129.0 

	TITLE	c:\users\przemyslaw.kleszcz\desktop\new folder (4)\memtest2\memtest_vect_vs2012\stdafx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	___@@_PchSym_@00@UfhvihUkiavnbhozdOpovhaxaUwvhpglkUmvdLulowviLSETUnvngvhgCUnvngvhgPevxgPehCABCUivovzhvUhgwzucOlyq@4B2008FD98C1DD4
;	COMDAT ___@@_PchSym_@00@UfhvihUkiavnbhozdOpovhaxaUwvhpglkUmvdLulowviLSETUnvngvhgCUnvngvhgPevxgPehCABCUivovzhvUhgwzucOlyq@4B2008FD98C1DD4
_BSS	SEGMENT
___@@_PchSym_@00@UfhvihUkiavnbhozdOpovhaxaUwvhpglkUmvdLulowviLSETUnvngvhgCUnvngvhgPevxgPehCABCUivovzhvUhgwzucOlyq@4B2008FD98C1DD4 DD 01H DUP (?)
_BSS	ENDS
END
